import { RestContext, RestRequest } from "msw"

const getReposPullDetails = {
  status200:(req: RestRequest, res: any, ctx: RestContext) => {
    return res(
      ctx.status(200),
      ctx.json(jsonReposPullDetails),
    )
  },
}

const jsonReposPullDetails = {
  "url": "https://api.github.com/repos/recharts/recharts/pulls/3304",
  "id": 1223510557,
  "node_id": "PR_kwDOAmegOs5I7Uod",
  "html_url": "https://github.com/recharts/recharts/pull/3304",
  "diff_url": "https://github.com/recharts/recharts/pull/3304.diff",
  "patch_url": "https://github.com/recharts/recharts/pull/3304.patch",
  "issue_url": "https://api.github.com/repos/recharts/recharts/issues/3304",
  "number": 3304,
  "state": "closed",
  "locked": false,
  "title": "feat: storybook integration",
  "user": {
    "login": "proke03",
    "id": 19148682,
    "node_id": "MDQ6VXNlcjE5MTQ4Njgy",
    "avatar_url": "https://avatars.githubusercontent.com/u/19148682?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/proke03",
    "html_url": "https://github.com/proke03",
    "followers_url": "https://api.github.com/users/proke03/followers",
    "following_url": "https://api.github.com/users/proke03/following{/other_user}",
    "gists_url": "https://api.github.com/users/proke03/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/proke03/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/proke03/subscriptions",
    "organizations_url": "https://api.github.com/users/proke03/orgs",
    "repos_url": "https://api.github.com/users/proke03/repos",
    "events_url": "https://api.github.com/users/proke03/events{/privacy}",
    "received_events_url": "https://api.github.com/users/proke03/received_events",
    "type": "User",
    "site_admin": false
  },
  "body": "<!--- Provide a general summary of your changes in the Title above -->\r\n\r\n## Description\r\nI couldn't migrate, so I created a new branch.\r\n\r\n<!--- Describe your changes in detail -->\r\n\r\n## Related Issue\r\n#3268\r\n<!--- This project only accepts pull requests related to open issues -->\r\n<!--- If suggesting a new feature or change, please discuss it in an issue first -->\r\n<!--- If fixing a bug, there should be an issue describing it with steps to reproduce -->\r\n<!--- Please link to the issue here: -->\r\n\r\n## Motivation and Context\r\n\r\n<!--- Why is this change required? What problem does it solve? -->\r\n\r\n## How Has This Been Tested?\r\nhttps://63d24aee84ee7cc215239dcc-jtfjcnhigf.chromatic.com/\r\n<!--- Please describe in detail how you tested your changes. -->\r\n<!--- Include details of your testing environment, and the tests you ran to -->\r\n<!--- see how your change affects other areas of the code, etc. -->\r\n\r\n## Screenshots (if appropriate):\r\n\r\n## Types of changes\r\n\r\n<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->\r\n\r\n- [ ] Bug fix (non-breaking change which fixes an issue)\r\n- [x] New feature (non-breaking change which adds functionality)\r\n- [ ] Breaking change (fix or feature that would cause existing functionality to change)\r\n\r\n## Checklist:\r\n\r\n<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->\r\n<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->\r\n\r\n- [ ] My code follows the code style of this project.\r\n- [ ] My change requires a change to the documentation.\r\n- [ ] I have updated the documentation accordingly.\r\n- [ ] I have added tests to cover my changes.\r\n- [ ] All new and existing tests passed.\r\n",
  "created_at": "2023-01-31T15:38:48Z",
  "updated_at": "2023-02-01T18:44:53Z",
  "closed_at": "2023-02-01T18:24:16Z",
  "merged_at": "2023-02-01T18:24:16Z",
  "merge_commit_sha": "1bd7779e42ef2e9bd92c2d6b5ce9e9fd2b55a574",
  "assignee": null,
  "assignees": [

  ],
  "requested_reviewers": [
    {
      "login": "nikolasrieble",
      "id": 27995606,
      "node_id": "MDQ6VXNlcjI3OTk1NjA2",
      "avatar_url": "https://avatars.githubusercontent.com/u/27995606?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nikolasrieble",
      "html_url": "https://github.com/nikolasrieble",
      "followers_url": "https://api.github.com/users/nikolasrieble/followers",
      "following_url": "https://api.github.com/users/nikolasrieble/following{/other_user}",
      "gists_url": "https://api.github.com/users/nikolasrieble/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nikolasrieble/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nikolasrieble/subscriptions",
      "organizations_url": "https://api.github.com/users/nikolasrieble/orgs",
      "repos_url": "https://api.github.com/users/nikolasrieble/repos",
      "events_url": "https://api.github.com/users/nikolasrieble/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nikolasrieble/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "requested_teams": [

  ],
  "labels": [

  ],
  "milestone": null,
  "draft": false,
  "commits_url": "https://api.github.com/repos/recharts/recharts/pulls/3304/commits",
  "review_comments_url": "https://api.github.com/repos/recharts/recharts/pulls/3304/comments",
  "review_comment_url": "https://api.github.com/repos/recharts/recharts/pulls/comments{/number}",
  "comments_url": "https://api.github.com/repos/recharts/recharts/issues/3304/comments",
  "statuses_url": "https://api.github.com/repos/recharts/recharts/statuses/1306388fa520238d9601c4983c70ea7d64cf8edf",
  "head": {
    "label": "proke03:feat/storybook-integration",
    "ref": "feat/storybook-integration",
    "sha": "1306388fa520238d9601c4983c70ea7d64cf8edf",
    "user": {
      "login": "proke03",
      "id": 19148682,
      "node_id": "MDQ6VXNlcjE5MTQ4Njgy",
      "avatar_url": "https://avatars.githubusercontent.com/u/19148682?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/proke03",
      "html_url": "https://github.com/proke03",
      "followers_url": "https://api.github.com/users/proke03/followers",
      "following_url": "https://api.github.com/users/proke03/following{/other_user}",
      "gists_url": "https://api.github.com/users/proke03/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/proke03/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/proke03/subscriptions",
      "organizations_url": "https://api.github.com/users/proke03/orgs",
      "repos_url": "https://api.github.com/users/proke03/repos",
      "events_url": "https://api.github.com/users/proke03/events{/privacy}",
      "received_events_url": "https://api.github.com/users/proke03/received_events",
      "type": "User",
      "site_admin": false
    },
    "repo": {
      "id": 593529210,
      "node_id": "R_kgDOI2CJeg",
      "name": "recharts",
      "full_name": "proke03/recharts",
      "private": false,
      "owner": {
        "login": "proke03",
        "id": 19148682,
        "node_id": "MDQ6VXNlcjE5MTQ4Njgy",
        "avatar_url": "https://avatars.githubusercontent.com/u/19148682?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/proke03",
        "html_url": "https://github.com/proke03",
        "followers_url": "https://api.github.com/users/proke03/followers",
        "following_url": "https://api.github.com/users/proke03/following{/other_user}",
        "gists_url": "https://api.github.com/users/proke03/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/proke03/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/proke03/subscriptions",
        "organizations_url": "https://api.github.com/users/proke03/orgs",
        "repos_url": "https://api.github.com/users/proke03/repos",
        "events_url": "https://api.github.com/users/proke03/events{/privacy}",
        "received_events_url": "https://api.github.com/users/proke03/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/proke03/recharts",
      "description": "Redefined chart library built with React and D3",
      "fork": true,
      "url": "https://api.github.com/repos/proke03/recharts",
      "forks_url": "https://api.github.com/repos/proke03/recharts/forks",
      "keys_url": "https://api.github.com/repos/proke03/recharts/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/proke03/recharts/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/proke03/recharts/teams",
      "hooks_url": "https://api.github.com/repos/proke03/recharts/hooks",
      "issue_events_url": "https://api.github.com/repos/proke03/recharts/issues/events{/number}",
      "events_url": "https://api.github.com/repos/proke03/recharts/events",
      "assignees_url": "https://api.github.com/repos/proke03/recharts/assignees{/user}",
      "branches_url": "https://api.github.com/repos/proke03/recharts/branches{/branch}",
      "tags_url": "https://api.github.com/repos/proke03/recharts/tags",
      "blobs_url": "https://api.github.com/repos/proke03/recharts/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/proke03/recharts/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/proke03/recharts/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/proke03/recharts/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/proke03/recharts/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/proke03/recharts/languages",
      "stargazers_url": "https://api.github.com/repos/proke03/recharts/stargazers",
      "contributors_url": "https://api.github.com/repos/proke03/recharts/contributors",
      "subscribers_url": "https://api.github.com/repos/proke03/recharts/subscribers",
      "subscription_url": "https://api.github.com/repos/proke03/recharts/subscription",
      "commits_url": "https://api.github.com/repos/proke03/recharts/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/proke03/recharts/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/proke03/recharts/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/proke03/recharts/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/proke03/recharts/contents/{+path}",
      "compare_url": "https://api.github.com/repos/proke03/recharts/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/proke03/recharts/merges",
      "archive_url": "https://api.github.com/repos/proke03/recharts/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/proke03/recharts/downloads",
      "issues_url": "https://api.github.com/repos/proke03/recharts/issues{/number}",
      "pulls_url": "https://api.github.com/repos/proke03/recharts/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/proke03/recharts/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/proke03/recharts/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/proke03/recharts/labels{/name}",
      "releases_url": "https://api.github.com/repos/proke03/recharts/releases{/id}",
      "deployments_url": "https://api.github.com/repos/proke03/recharts/deployments",
      "created_at": "2023-01-26T08:26:24Z",
      "updated_at": "2023-01-28T06:35:38Z",
      "pushed_at": "2023-02-01T17:32:51Z",
      "git_url": "git://github.com/proke03/recharts.git",
      "ssh_url": "git@github.com:proke03/recharts.git",
      "clone_url": "https://github.com/proke03/recharts.git",
      "svn_url": "https://github.com/proke03/recharts",
      "homepage": "http://recharts.org",
      "size": 12155,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "TypeScript",
      "has_issues": false,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "master"
    }
  },
  "base": {
    "label": "recharts:master",
    "ref": "master",
    "sha": "322c4b6b8a3a8d678ed0d901af5269c9fbc67674",
    "user": {
      "login": "recharts",
      "id": 13690587,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNjkwNTg3",
      "avatar_url": "https://avatars.githubusercontent.com/u/13690587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/recharts",
      "html_url": "https://github.com/recharts",
      "followers_url": "https://api.github.com/users/recharts/followers",
      "following_url": "https://api.github.com/users/recharts/following{/other_user}",
      "gists_url": "https://api.github.com/users/recharts/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/recharts/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/recharts/subscriptions",
      "organizations_url": "https://api.github.com/users/recharts/orgs",
      "repos_url": "https://api.github.com/users/recharts/repos",
      "events_url": "https://api.github.com/users/recharts/events{/privacy}",
      "received_events_url": "https://api.github.com/users/recharts/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "repo": {
      "id": 40345658,
      "node_id": "MDEwOlJlcG9zaXRvcnk0MDM0NTY1OA==",
      "name": "recharts",
      "full_name": "recharts/recharts",
      "private": false,
      "owner": {
        "login": "recharts",
        "id": 13690587,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNjkwNTg3",
        "avatar_url": "https://avatars.githubusercontent.com/u/13690587?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/recharts",
        "html_url": "https://github.com/recharts",
        "followers_url": "https://api.github.com/users/recharts/followers",
        "following_url": "https://api.github.com/users/recharts/following{/other_user}",
        "gists_url": "https://api.github.com/users/recharts/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/recharts/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/recharts/subscriptions",
        "organizations_url": "https://api.github.com/users/recharts/orgs",
        "repos_url": "https://api.github.com/users/recharts/repos",
        "events_url": "https://api.github.com/users/recharts/events{/privacy}",
        "received_events_url": "https://api.github.com/users/recharts/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/recharts/recharts",
      "description": "Redefined chart library built with React and D3",
      "fork": false,
      "url": "https://api.github.com/repos/recharts/recharts",
      "forks_url": "https://api.github.com/repos/recharts/recharts/forks",
      "keys_url": "https://api.github.com/repos/recharts/recharts/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/recharts/recharts/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/recharts/recharts/teams",
      "hooks_url": "https://api.github.com/repos/recharts/recharts/hooks",
      "issue_events_url": "https://api.github.com/repos/recharts/recharts/issues/events{/number}",
      "events_url": "https://api.github.com/repos/recharts/recharts/events",
      "assignees_url": "https://api.github.com/repos/recharts/recharts/assignees{/user}",
      "branches_url": "https://api.github.com/repos/recharts/recharts/branches{/branch}",
      "tags_url": "https://api.github.com/repos/recharts/recharts/tags",
      "blobs_url": "https://api.github.com/repos/recharts/recharts/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/recharts/recharts/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/recharts/recharts/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/recharts/recharts/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/recharts/recharts/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/recharts/recharts/languages",
      "stargazers_url": "https://api.github.com/repos/recharts/recharts/stargazers",
      "contributors_url": "https://api.github.com/repos/recharts/recharts/contributors",
      "subscribers_url": "https://api.github.com/repos/recharts/recharts/subscribers",
      "subscription_url": "https://api.github.com/repos/recharts/recharts/subscription",
      "commits_url": "https://api.github.com/repos/recharts/recharts/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/recharts/recharts/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/recharts/recharts/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/recharts/recharts/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/recharts/recharts/contents/{+path}",
      "compare_url": "https://api.github.com/repos/recharts/recharts/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/recharts/recharts/merges",
      "archive_url": "https://api.github.com/repos/recharts/recharts/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/recharts/recharts/downloads",
      "issues_url": "https://api.github.com/repos/recharts/recharts/issues{/number}",
      "pulls_url": "https://api.github.com/repos/recharts/recharts/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/recharts/recharts/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/recharts/recharts/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/recharts/recharts/labels{/name}",
      "releases_url": "https://api.github.com/repos/recharts/recharts/releases{/id}",
      "deployments_url": "https://api.github.com/repos/recharts/recharts/deployments",
      "created_at": "2015-08-07T06:50:27Z",
      "updated_at": "2023-02-01T21:10:42Z",
      "pushed_at": "2023-02-01T22:08:03Z",
      "git_url": "git://github.com/recharts/recharts.git",
      "ssh_url": "git@github.com:recharts/recharts.git",
      "clone_url": "https://github.com/recharts/recharts.git",
      "svn_url": "https://github.com/recharts/recharts",
      "homepage": "http://recharts.org",
      "size": 11439,
      "stargazers_count": 19654,
      "watchers_count": 19654,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": true,
      "has_discussions": true,
      "forks_count": 1497,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 439,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "charting-library",
        "d3",
        "react",
        "recharts"
      ],
      "visibility": "public",
      "forks": 1497,
      "open_issues": 439,
      "watchers": 19654,
      "default_branch": "master"
    }
  },
  "_links": {
    "self": {
      "href": "https://api.github.com/repos/recharts/recharts/pulls/3304"
    },
    "html": {
      "href": "https://github.com/recharts/recharts/pull/3304"
    },
    "issue": {
      "href": "https://api.github.com/repos/recharts/recharts/issues/3304"
    },
    "comments": {
      "href": "https://api.github.com/repos/recharts/recharts/issues/3304/comments"
    },
    "review_comments": {
      "href": "https://api.github.com/repos/recharts/recharts/pulls/3304/comments"
    },
    "review_comment": {
      "href": "https://api.github.com/repos/recharts/recharts/pulls/comments{/number}"
    },
    "commits": {
      "href": "https://api.github.com/repos/recharts/recharts/pulls/3304/commits"
    },
    "statuses": {
      "href": "https://api.github.com/repos/recharts/recharts/statuses/1306388fa520238d9601c4983c70ea7d64cf8edf"
    }
  },
  "author_association": "CONTRIBUTOR",
  "auto_merge": null,
  "active_lock_reason": null,
  "merged": true,
  "mergeable": null,
  "rebaseable": null,
  "mergeable_state": "unknown",
  "merged_by": {
    "login": "ckifer",
    "id": 25180830,
    "node_id": "MDQ6VXNlcjI1MTgwODMw",
    "avatar_url": "https://avatars.githubusercontent.com/u/25180830?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ckifer",
    "html_url": "https://github.com/ckifer",
    "followers_url": "https://api.github.com/users/ckifer/followers",
    "following_url": "https://api.github.com/users/ckifer/following{/other_user}",
    "gists_url": "https://api.github.com/users/ckifer/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ckifer/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ckifer/subscriptions",
    "organizations_url": "https://api.github.com/users/ckifer/orgs",
    "repos_url": "https://api.github.com/users/ckifer/repos",
    "events_url": "https://api.github.com/users/ckifer/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ckifer/received_events",
    "type": "User",
    "site_admin": false
  },
  "comments": 2,
  "review_comments": 9,
  "maintainer_can_modify": false,
  "commits": 20,
  "additions": 41605,
  "deletions": 5285,
  "changed_files": 24
}

export {getReposPullDetails, jsonReposPullDetails}